### ISSUE TITLE
さっくりとプラグインを使ってみた感じのレビューを書いておきます

### ISSUE THREAD

**Issue by wate** [junichi11/netbeans-image-placeholder#1]
最初に使ってみた第1印象で以下の2つが気になりました。
- プラグインと言うよりも、placekitten側の問題ではあるんですが、  
  placekittenを選択してgrayにチェックを入れないと画像が表示できません
- 「Update preview」ボタンを押さなくても自動でプレビューが切り替わるとありがたいです

実際に書いているimgタグの内容などを元に以下のような項目を、
ついでに設定出来れば便利かなと思うものを以下に記載しています
※別に無くても気にならないレベルの要望です
- 現在の「OK」と「取り消し」ボタンの位置に「Insert img tag」と「Copy」ボタンがあると  
  操作がしやすいと思います。  
  ※imgタグを貼り付けるつもりで何度か「OK」ボタンを押しちゃいました・・・
- imgタグ生成時にwidthとheight属性が付与されてると助かるかも  
  ※画像の最大サイズの仕様替わりにタグに属性として書いてる時があったりします
- alt属性を自分で指定できるようになっているといいかも  
  ※「後でここを差し替え！」とかをalt属性に入れてたりする時があったりします
- 任意でtitle属性を指定できるようになっているといいかも  
  ※[colorbox](http://www.jacklmoore.com/colorbox/)などlitebox系プラグインを利用することを想定して、  
  事前にtitle属性だけ設定しておく場合があったりします

**Comment by junichi11** [comment]
> placekittenを選択してgrayにチェックを入れないと画像が表示できません

おそらく画像のサイズの問題だと思われます。値によって表示されないものがあるような気がします。デフォルト値がlorempixelと同じになっていると思うのでデフォルトの値を修正します。

> 「Update preview」ボタンを押さなくても自動でプレビューが切り替わるとありがたいです

これは最初に実装しましたが、値をリスナーで監視しているため、スピナーで値を変更されたりするとその回数分画像を取りにいくことになると思うので、手動でアップデートするように変更しました。影響はほとんどないとは思いますが、提供している側からすると無駄なアクセスはあまりしてほしくないのではないのかなと。。。

一番いいのは、管理者にこのような使い方をしてもいいのか聞くことですが、新しいものを追加するたびに聞いて変更するのはちょっと手間がかかる（OKなものとNGなものが混ざると混乱するので）ので避けたいです。

１つの案としては、タイマーをセット(1〜2秒後に実行)して、時間内に値が更新された場合はキャンセルして、またタイマーをセットし直すというのが考えられます。

うーん、どうしましょうかね。。。

> 現在の「OK」と「取り消し」ボタンの位置に「Insert img tag」と「Copy」ボタンがあると操作がしやすいと思います。

~~簡単のためダイアログ部分をNetBeansのapiを使って実装しているので、その部分の変更は少しお待ちください。修正するかどうかはまだわかりませんが、もし変更するとしたら、直接入れることができないので（ボタン部分は変更できないので）、新たにDialogを作成して「Close」ボタンを追加する形になると思います。~~ 間違いです。修正します。

> imgタグ生成時にwidthとheight属性が付与されてると助かるかも
> alt属性を自分で指定できるようになっているといいかも
> 任意でtitle属性を指定できるようになっているといいかも

追加しますね。

**Comment by junichi11** [comment]
すみません。私の思い違いで、ダイアログのボタン部分は変更出来ましたので、ボタン部分は後ほど変更しようと思います。

**Comment by junichi11** [comment]
ダイアログのボタンは画像のように変更します。
![nb-image-placeholder-dialog-options](https://cloud.githubusercontent.com/assets/738383/6506512/07f53ecc-c38f-11e4-9066-63995bdf02e4.png)

**Comment by wate** [comment]
諸々、了解です！

**Comment by junichi11** [comment]
@wate いつも丁寧なレビューをありがとうございます！自動更新以外は修正してみました。 
alt, title属性の設定値は共通の値にしていて、保存をボタンを押しても保存されないようになっています。

自動更新は便利なので、できれば実装したいのですが、保留という事でよろしいでしょうか？

https://github.com/junichi11/netbeans-image-placeholder/releases/tag/v0.0.2

**Comment by wate** [comment]
> 自動更新は便利なので、できれば実装したいのですが、保留という事でよろしいでしょうか？

(≧∇≦)b OK

**Comment by junichi11** [comment]
Plugin Portal へ登録しました。時間が経てば公開されると思います。

**Comment by wate** [comment]
∠(￣◇￣)   らじゃ～
